name: portfolio_web
description: Modern Flutter Web Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  image_path: "assets/sm_logo.png"
  web:
    generate: true
    image_path: "assets/sm_logo.png"
    background_color: "#ffffff"
    theme_color: "#000000"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true